"""Generate the per-standard nginx routing include (cairn-routes.conf).

The static base config (deploy/nginx.conf) provides MIME types, CORS, caching, content
negotiation maps, and error pages. This module generates only the parts that depend on the
manifests: the namespace documents, the pin-to-latest 303 redirects, and 410s for withdrawn
versions. The result is ``include``-d inside the server block.
"""

from __future__ import annotations

from pathlib import Path

from .config import nginx_routes_path
from .manifest import Standard
from .util import atomic_write, reap_temp_files


def _standard_block(std: Standard) -> str:
    lines: list[str] = [f"# ===================== {std.id} =====================",
                        f"location = /{std.id} {{ try_files /{std.id}/index.html =404; }}"]

    for ml in std.sorted_major_lines():
        v = ml.major
        latest = ml.latest
        # Namespace document for the major line. Browsers (and anything not explicitly asking
        # for XML) get the human-readable RDDL page; XML tools that send Accept: application/xml
        # are content-negotiated straight to the current schema.
        lines += [
            f"location = /{std.id}/v{v} {{",
            f"    if ($cairn_wants_xml) {{ return 303 /{std.id}/v{latest}/{_schema_name(std, latest)}; }}",
            f"    default_type application/xhtml+xml;",
            f"    try_files /{std.id}/_ns/v{v}.xhtml =404;",
            f"}}",
            # Pin-to-latest: any file requested under the major line redirects to the concrete
            # latest release. Note /{id}/v{major}.y.z/... does NOT match this (no '/' after vN).
            f'location ~ "^/{std.id}/v{v}/(?<cairn_rest>.+)$" {{ return 303 /{std.id}/v{latest}/$cairn_rest; }}',
        ]

    for rel in std.releases:
        if not rel.is_served:
            ver = rel.version.replace(".", r"\.")
            lines.append(
                f'location ~ "^/{std.id}/v{ver}(/.*)?$" {{ return 410; }}'
            )

    lines.append("")
    return "\n".join(lines)


def _schema_name(std: Standard, version: str) -> str:
    """The primary schema artifact name for a release (used as the content-neg target)."""
    rel = std.release(version)
    if rel:
        for art in rel.artifacts:
            if art.role == "schema":
                return art.name
        if rel.artifacts:
            return rel.artifacts[0].name
    return f"{std.id}.xsd"


def render_routes(standards: list[Standard]) -> str:
    header = (
        "# Generated by `cairn build` - do not edit by hand.\n"
        "# Included inside the server{} block of deploy/nginx.conf.\n\n"
    )
    return header + "\n".join(_standard_block(s) for s in standards)


def write_routes(standards: list[Standard], root: Path) -> Path:
    # Atomic like every other generated file. A truncated include is worse than a stale one:
    # the web container reloads on any change to this file, and nginx refuses a config it
    # cannot parse, so a kill mid-write leaves the running worker on the old config and the
    # next restart unable to start at all.
    out = nginx_routes_path(root)
    # Same argument as the document root: this volume is written by the syncer container and
    # read by the web one, so a directory left at the writer's umask is a config the reader
    # cannot open when the two run as different uids.
    out.parent.mkdir(parents=True, exist_ok=True)
    # This directory is under neither reaper: the sync only sweeps release directories and
    # the render only sweeps the document root, while the routes file lives outside both.
    # Writing it is the last thing a build does, so a kill here is the likeliest one.
    reap_temp_files(out.parent)
    atomic_write(out, render_routes(standards).encode("utf-8"))
    return out
